/* Session 4: math tokens compile to offline MathML via spec/lesson-four-math.json. */
window.renderLessonFour = function(host,state,save,onComplete){
  const pages=[
    {
      title:'Recall: turn a count into an estimate',time:'5 minutes',
      body:`<p>This is the scheduled recall of lesson 1, followed by a new application of lesson 3's bound. You will estimate an unknown fraction without enumerating every possible object.</p><p>The six sections take about 60 minutes, including a real past-exam problem on paper. Nothing depends on a score.</p><p>Each of N independent trials succeeds with probability p. Let each success indicator be ⟦s4.indicator⟧, and define</p><p>⟦s4.sum⟧</p><p>⟦s4.mean⟧</p><p>The count X grows with the number of trials. To estimate a proportion, divide by the number of trials:</p><p>⟦s4.estimate⟧</p><p>The hat means “estimate”: ⟦s4.phat⟧ is computed from samples; p is the unknown true fraction.</p>`,
      checks:[{id:'estimate-mean',prompt:'What is the expected value of the sample fraction?',options:[
        ['⟦s4.expected-estimate⟧',true,'Linearity gives ⟦s4.mean⟧. Dividing by N gives ⟦s4.expected-estimate⟧. This does not guarantee that each estimate equals p.'],
        ['⟦s4.mean⟧',false,'That is the expectation of the count, not the fraction. The estimator divides the count by N.'],
        ['It always equals one half.',false,'That would require p to be one half. Indicators can have any success probability between zero and one.']
      ]}]
    },
    {
      title:'Define exactly what you are sampling',time:'10 minutes',
      body:`<p>Let ⟦s4.space⟧ be a finite collection of objects and ⟦s4.good⟧ the ones with a desired property. We want to estimate</p><p>⟦s4.fraction⟧</p><p>Sample uniformly from <strong>all</strong> of ⟦s4.space⟧, not only from the good objects. For each sample, test whether it belongs to A and record one or zero.</p><p>⟦s4.single⟧</p><p>Repeat independently, with replacement. A repeated object is allowed; the fresh random choices make the trials independent. Return the fraction of successes:</p><p>⟦s4.estimate⟧</p><p>The proof requires two separate facts: the distribution is uniform, so its success probability is p; and the trials are independent, so the Chernoff theorem applies.</p><div class="example"><p><strong>Example.</strong> To estimate the fraction of Boolean assignments satisfying a formula, independently choose each variable true or false with equal probability. Test the whole formula. Repeating this with fresh choices samples all assignments uniformly, even when very few satisfy it.</p></div><p>Efficient sampling and testing are also required for an efficient algorithm. An enormous sample space does not by itself force enumeration.</p>`,
      checks:[{id:'sample-space',prompt:'To estimate the fraction of assignments satisfying a formula, which sample space should you use?',options:[
        ['All assignments, chosen uniformly.',true,'Then the success indicator has expectation equal to the fraction you want. Test satisfaction after sampling.'],
        ['Only satisfying assignments.',false,'Every tested sample would succeed, estimating one rather than the fraction among all assignments. Finding such samples may also be difficult.'],
        ['Any convenient set of assignments, with any distribution.',false,'Without uniform sampling or a justified correction, the sample success probability need not equal the desired fraction.']
      ]},{id:'fresh-samples',prompt:'Can you sample one assignment and reuse its success result N times for this proof?',options:[
        ['Yes; each copy has the same success probability.',false,'The copies are completely dependent. They do not supply N independent indicators, so this Chernoff calculation cannot be used.'],
        ['No; use fresh independent samples.',true,'Replacement allows accidental repeats, but the sampling choices must still be independent. Reusing one random outcome is different.']
      ]}]
    },
    {
      title:'Convert estimation error into a tail event',time:'10 minutes',
      body:`<p>The requested accuracy and failure tolerance are</p><p>⟦s4.bounds⟧</p><p>⟦s4.goal⟧</p><p>Here ⟦s4.epsilon⟧ is an <strong>additive error in the fraction</strong>, and ⟦s4.eta⟧ is the allowed failure probability.</p><div class="worked-line"><strong>1. Rewrite the bad event using the count.</strong><p>Since N is positive, multiply the error inequality by N:</p><p>⟦s4.equivalence⟧</p></div><div class="worked-line"><strong>2. Apply the sheet's fractional Chernoff bound.</strong><p>⟦s4.chernoff⟧</p><p>Our strict bad event is contained in the non-strict event on the sheet. Since ⟦s4.mean⟧,</p><p>⟦s4.failure⟧</p></div><div class="worked-line"><strong>3. Choose enough samples.</strong><p>Require</p><p>⟦s4.target⟧</p><p>Take natural logarithms, then divide by the negative coefficient, reversing the inequality:</p><p>⟦s4.exponent⟧</p><p>⟦s4.size⟧</p><p>Choose an integer by rounding up:</p><p>⟦s4.integer-size⟧</p></div><p>The sample size does not require knowing p. Accuracy enters through its inverse square; confidence enters through a logarithm.</p>`,
      checks:[{id:'count-threshold',prompt:'An error of ⟦s4.epsilon⟧ in the fraction corresponds to what absolute deviation in the count?',options:[
        ['⟦s4.deviation⟧',true,'The estimator is the count divided by N. Multiplying both sides of the error inequality by N yields ⟦s4.deviation⟧.'],
        ['⟦s4.epsilon⟧',false,'That leaves the threshold on the scale of the fraction. The count is N times the fraction.'],
        ['⟦s4.wrong-deviation⟧',false,'You need to multiply by N to undo the division in the estimator, not divide a second time.']
      ]},{id:'relative-error',prompt:'Does this proof also establish the relative-error statement ⟦s4.relative⟧?',options:[
        ['Yes; additive and relative error are the same.',false,'Relative error scales the tolerance by p. For small p it is a much stronger demand, and is not implied by this additive guarantee.'],
        ['No; it establishes ⟦s4.accuracy⟧.',true,'Keep the requested additive guarantee. A small additive error can still be a large fraction of a tiny p.']
      ]}]
    },
    {
      title:'Worked algorithm: choose N and account for runtime',time:'10 minutes',
      body:`<p><strong>Task.</strong> Estimate a fraction to additive error at most one tenth, with failure probability at most one twentieth. Assume uniform sampling and property testing are available.</p><p>⟦s4.parameters⟧</p><div class="worked-line"><strong>1. Set the sample size.</strong><p>⟦s4.numeric-size⟧</p></div><div class="worked-line"><strong>2. Run and return.</strong><p>Draw 185 independent uniform samples. Count those with the desired property, and return the count divided by 185. For example, 74 successful samples give:</p><p>⟦s4.sample-example⟧</p></div><div class="worked-line"><strong>3. State the guarantee over sampling randomness.</strong><p>⟦s4.numeric-check⟧</p><p>Therefore the output is within one tenth of p with probability at least 0.95. The particular output 0.4 is an observation, not a certificate that its error is small on this run.</p></div><div class="worked-line"><strong>4. Include all work.</strong><p>If generating one sample costs ⟦s4.tsample⟧ and testing it costs ⟦s4.tcheck⟧, the total is</p><p>⟦s4.runtime⟧</p><p>The extra constant term includes counting. Use the arithmetic-cost model specified by the problem; do not call the algorithm efficient without checking the sampling and testing costs.</p></div><p>If the question instead asks for the <em>number</em> of good objects, multiplying by the space size gives ⟦s4.counting⟧, with additive error at most ⟦s4.count-error⟧. This is not an exact count.</p>`,
      checks:[{id:'sampling-runtime',prompt:'Is “runtime is O(N)” always sufficient?',options:[
        ['Yes; we repeat the experiment N times.',false,'Each repetition may require generating a long object and testing a nontrivial property. Include those costs.'],
        ['Only if the work per trial is constant in the relevant input size.',true,'Otherwise multiply the sample count by the generation and checking costs.']
      ]}]
    },
    {
      title:'Practice A · budget error across several estimates',time:'10 minutes',
      body:`<p>You want M estimated proportions, each accurate to additive error ⟦s4.epsilon⟧, with probability at least one minus ⟦s4.eta⟧ that <strong>all</strong> are accurate.</p><p>For each property, use N samples independent across trials. The same trial objects may be reused for different properties. This can make the different estimates dependent, which is allowed by the union bound.</p><p>Starting with the per-estimate bound, write the union bound on paper:</p><p>⟦s4.union⟧</p><p>Equivalently, budget at most ⟦s4.budget⟧ failure per estimate. A sufficient sample size per estimate is</p><p>⟦s4.multi-size⟧</p><p>Now use ⟦s4.multi-values⟧ and fill the gaps below. Numeric fields accept fractions or decimals.</p>`,
      numeric:[
        {id:'accuracy-scale',label:'Keeping confidence fixed, halving the allowed additive error multiplies the unrounded sample-size threshold by what factor?',value:4,correct:'The threshold is proportional to the inverse square of the error. Halving it multiplies the threshold by ⟦s4.four⟧. Integer ceilings can alter the exact rounded ratio.',wrong:'Square the factor from halving the error: the threshold contains the error squared in its denominator.'},
        {id:'union-log',label:'For the stated parameters, what number goes inside the logarithm, 2M divided by the failure tolerance?',value:4000,correct:'The value of ⟦s4.multi-inside⟧ is ⟦s4.4000⟧. Thus ⟦s4.multi-final⟧ samples per estimate suffice.',wrong:'Use all 100 estimates and the failure tolerance one twentieth: multiply 2 by 100, then divide by one twentieth.'}
      ],
      checks:[{id:'reuse-estimates',prompt:'Must estimates of different properties be independent to apply the union bound?',options:[
        ['No; independence is required across trials inside each Chernoff application.',true,'Different estimates may use the same sample objects. Their bad events can be dependent; the union bound still adds their failure probabilities.'],
        ['Yes; the union bound needs independent events.',false,'The union bound has no independence requirement. Distinguish it from the independence used for each estimator’s sum.']
      ]}],
      end:`<details><summary>Compare the completed parameter calculation</summary><p>For M properties, the failure bound is ⟦s4.union⟧. Solving for the desired total tolerance gives ⟦s4.multi-size⟧. Substituting the stated parameters gives ⟦s4.multi-final⟧. With this many independent trials, all estimates meet their additive-error targets with probability at least 0.95.</p></details>`
    },
    {
      title:'Practice B · an actual exam sampling problem',time:'15 minutes',
      body:`<p><strong>2025B, Problem 5 — restated.</strong> Let G be an undirected graph, with ⟦s4.graph⟧ and ⟦s4.n-positive⟧. A three-coloring assigns a color to every vertex:</p><p>⟦s4.color-def⟧</p><p>It is legal when</p><p>⟦s4.legal⟧</p><p>Define the fraction of all colorings that are legal:</p><p>⟦s4.color-proportion⟧</p><p>Give a randomized polynomial-time algorithm outputting a number A(G) such that</p><p>⟦s4.exam-goal⟧</p><p>Describe sampling, the estimator, the sample size, the probability proof, and runtime. Use about ten minutes for a paper attempt and five for comparison. The <a href="../Exams/Exams/2025B.pdf#page=8">original question</a> is available separately.</p><details><summary>Hint 1 · sampling uniformly</summary><p>Choose every vertex's color independently and uniformly from the three colors. This generates each complete coloring with probability ⟦s4.one-color⟧. Test legality by scanning edges.</p></details><details><summary>Hint 2 · choose the indicator and parameters</summary><p>One indicator represents a <strong>whole sampled coloring being legal</strong>, not an individual edge being correctly colored. Use ⟦s4.exam-params⟧.</p></details><details><summary>Hint 3 · the sample size</summary><p>Substitute the error and failure targets into ⟦s4.integer-size⟧ and simplify the logarithm. One valid choice is ⟦s4.exam-N⟧.</p></details><p>Your written proof is checked with the rubric, not automatically graded.</p>`,
      checks:[],
      end:`<details><summary>Compare · algorithm and estimator</summary><p>Draw N independent complete colorings by independently assigning each vertex a uniform color. Each coloring has probability ⟦s4.one-color⟧. Let the ith indicator be one if every edge has differently colored endpoints, and zero otherwise. Its expectation is ⟦s4.R⟧.</p><p>Let X be the number of legal samples. Return ⟦s4.exam-output⟧, using ⟦s4.exam-N⟧ samples.</p><p>Do not count the proportion of individually legal edges. That is a different quantity from the proportion of complete legal colorings.</p></details><details><summary>Compare · error and confidence</summary><p>The independent sample indicators have common mean ⟦s4.R⟧. Translating fraction error into count error and using Chernoff gives</p><p>⟦s4.exam-bound⟧</p><p>Our sample size ensures</p><p>⟦s4.exam-simplify⟧</p><p>Taking the complement proves ⟦s4.exam-goal⟧. No knowledge of ⟦s4.R⟧ was required to choose the sample size.</p></details><details><summary>Compare · polynomial runtime and limits</summary><p>Generating one coloring and testing all edges takes ⟦s4.graph-pass⟧ under the usual constant-time random-color and graph-access model. Total time is</p><p>⟦s4.exam-time⟧</p><p>There are ⟦s4.colors⟧ possible colorings, but the algorithm samples without enumerating them. The guarantee is additive. A returned zero does not certify that the graph has no legal coloring.</p><p>This derivation supplies explicit constants and runtime details for the method in the <a href="../Exams/Solutions/2025solB.pdf#page=8">official solution</a>.</p></details><section class="panel"><h3>Check the proof on your page</h3><p>Mark the arguments actually present. Repair a missing step, then reconstruct it with the comparison closed.</p><div id="paper-rubric"></div><p id="rubric-status" role="status"></p></section><p class="prompt">Define the sampling space → test one whole object → average independent indicators → translate the error event → choose N → account for runtime.</p><p>Next is the fixed Karger session. No extra work is assigned based on your answers.</p>`
    }
  ];
  window.renderGuidedLesson(host,state,save,onComplete,{pages,number:4,stateKey:'lessonFour',typeset:true,
    source:'<p>The concentration bound follows page 1 of the <a href="../Advanced_Algorithms_Formula_Sheet.pdf#page=1">formula sheet</a>. Practice B restates <a href="../Exams/Exams/2025B.pdf#page=8">2025B Problem 5</a>; its official solution uses this sampling method. Earlier worked examples are authored teaching exercises.</p>',
    rubric:[
      ['sampling','I sampled complete colorings uniformly and independently across trials.'],
      ['indicator','My indicator tests the legality of an entire coloring, and has expectation ⟦s4.R⟧.'],
      ['estimator','I returned the sample fraction ⟦s4.exam-output⟧.'],
      ['size','I chose a sufficient explicit polynomial sample size, such as ⟦s4.exam-N⟧.'],
      ['probability','I translated the error into a tail event and proved ⟦s4.exam-goal⟧.'],
      ['runtime','I included both generation and checking costs in ⟦s4.exam-time⟧.']
    ]});
};
