#!/usr/bin/env python3
"""Compile authored question hints to offline MathML. Never infer hints from summaries."""
import json
from pathlib import Path
from build_guides import render_math

ROOT = Path(__file__).resolve().parents[1]

def unique(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f'Duplicate hint key: {key}')
        result[key] = value
    return result

def read(path):
    return json.loads(path.read_text(), object_pairs_hook=unique)

def build():
    data = read(ROOT / 'data/questions.json')
    keys = {g['sid'] + '#' + (p['part'] or 'x')
            for u in data['units'] for t in u['topics'] for g in t['groups'] for p in g['parts']}
    tools = read(ROOT / 'data/hints/tools.json')
    result = {}
    for path in sorted((ROOT / 'data/hints').glob('questions-*.json')):
        for key, row in read(path).items():
            assert key in keys and key not in result, key
            assert len(row) == 4 and all(isinstance(x, str) and x.strip() for x in row), key
            tool, start, next_step, check = row
            explain, structure = tools[tool]
            steps = [start, explain, next_step, structure, check]
            html = [render_math('<p>' + text + '</p>') for text in steps]
            assert all('<code>' not in text and '\\(' not in text and '\\[' not in text for text in html), key
            result[key] = html
    missing = keys - result.keys()
    assert not missing, f'Missing hints: {sorted(missing)}'
    (ROOT / 'hints.js').write_text('/* Generated by spec/build_hints.py. */\nwindow.HINTS = ' + json.dumps(result, ensure_ascii=False) + ';\n')
    print(f'Built five-step hint ladders for {len(result)}/{len(keys)} question parts.')

if __name__ == '__main__':
    build()
