#!/usr/bin/env python3
"""Compile the course notation map to native offline MathML, as build_guides.py does."""
import json
from pathlib import Path
from latex2mathml.converter import convert

root = Path(__file__).resolve().parent.parent
source = json.loads((root / 'spec/course-math.json').read_text())
for path in sorted((root / 'spec').glob('lesson-*-math.json')):
    additions = json.loads(path.read_text())
    overlap = source.keys() & additions.keys()
    if overlap:
        raise ValueError(f'Duplicate math keys in {path}: {overlap}')
    source.update(additions)
formulas = {text: convert(tex) for text, tex in source.items()}
(root / 'course-math.js').write_text(
    '/* Generated by spec/build_course_math.py. */\nwindow.COURSE_MATH = '
    + json.dumps(formulas, ensure_ascii=False) + ';\n'
)
print(f'Compiled {len(formulas)} course formulas')
