#!/usr/bin/env python3
"""Assemble StudySite/intel.js (the Exam Intel tab) from data/intel/intel2026C.json
(practice problems) and the briefing HTML it names in "overviewFile".

Math is authored in LaTeX with \\( ... \\) (inline) and \\[ ... \\] (display) and is
converted to MathML at build time, exactly as build_guides.py does (native browser
rendering, no runtime library). The `summary` field of a part is shown as escaped
plain text by app.js, so it must not contain LaTeX."""
import json, os, re, sys
from latex2mathml.converter import convert

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # StudySite/

SRC = "data/intel/intel2026C.json"
HTML_FIELDS = ("overview", "blurb", "stem", "q", "basis", "sol", "srcline", "src")
failures = []

def to_mathml(latex, block):
    try:
        m = convert(latex.strip())
    except Exception as e:
        failures.append(latex.strip()[:60])
        sys.stderr.write(f"  math FAIL: {latex[:60]!r}: {e}\n")
        return '<code>' + latex.strip() + '</code>'
    if block:
        m = m.replace('display="inline"', 'display="block"', 1)
    return m

def render_math(html):
    html = re.sub(r'\\\[(.+?)\\\]', lambda m: '<div class="gmath">' + to_mathml(m.group(1), True) + '</div>',
                  html, flags=re.S)
    return re.sub(r'\\\((.+?)\\\)', lambda m: to_mathml(m.group(1), False), html, flags=re.S)

def walk(node):
    if isinstance(node, dict):
        return {k: (render_math(v) if k in HTML_FIELDS and isinstance(v, str) else walk(v)) for k, v in node.items()}
    if isinstance(node, list):
        return [walk(x) for x in node]
    return node

def build():
    data = json.load(open(SRC, encoding="utf-8"))
    if "overviewFile" in data:  # the briefing is authored as a separate HTML file
        data["overview"] = open(data.pop("overviewFile"), encoding="utf-8").read()
    for sec in data["sections"]:
        for it in sec["items"]:
            for pt in it["parts"]:
                if "\\(" in pt.get("summary", "") or "\\[" in pt.get("summary", ""):
                    sys.exit(f"LaTeX in summary of {it['id']} part {pt.get('part')}: summaries are plain text")
    out = walk(data)
    with open("intel.js", "w", encoding="utf-8") as f:
        f.write("/* Generated by spec/build_intel.py from " + SRC + " - edit the JSON, not this file. */\n")
        f.write("window.INTEL = " + json.dumps(out, ensure_ascii=False) + ";\n")
    n_items = sum(len(s["items"]) for s in data["sections"])
    n_parts = sum(len(it["parts"]) for s in data["sections"] for it in s["items"])
    print(f"wrote intel.js - {len(data['sections'])} sections, {n_items} problems, {n_parts} parts")
    if failures:
        sys.exit(f"{len(failures)} formula(s) failed to convert")

if __name__ == "__main__":
    build()
